import './globals.css';
import { Inter } from 'next/font/google';
import '@wordpress/components/build-style/style.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'WPUI Using NEXT',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
          {children}
        </div>
      </body>
    </html>
  )
}
